### ISSUE TITLE
Can use dynstack for non-dyn data

### ISSUE THREAD

**Issue by diwic** [archshift/dynstack#1]
This test compiles and runs just fine:

    #[test]
    fn test_non_dyn() {
        let mut stack: DynStack<u8> = DynStack::new();
        for _ in 0..15 { dyn_push!(stack, 5u8); }
        let x = stack[14];
        println!("{:?}", x);
    }

...but I'm quite sure it does dumb things internally, by composing and decomposing fat pointers for things where there are no fat pointers?

**Comment by archshift** [comment]
I don't think I can prevent this at compile time, though it can easily be asserted. I'm not actually sure it's necessary though.

We do end up interpreting a `*mut SizedStruct` as a fat pointer, but we'd never dereference the latter half of the pointer, (which would contain some stack garbage). Unless maybe the pointer sits in memory on some memory protection boundary, where overreading it by an extra word would be a problem?

**Comment by diwic** [comment]
> Unless maybe the pointer sits in memory on some memory protection boundary, where overreading it by an extra word would be a problem?

Yeah, that was my thought as well. But it seems hard to trigger because `dyn_push!` copies the item to the stack before pushing it...
