### ISSUE TITLE
Alloc free behind feature flag?

### ISSUE THREAD

**Issue by MathiasKoch** [archshift/dynstack#14]
Would you be open to a PR adding support for a heapless version behind an `alloc` feature flag, using `heapless::Vec`?

If this is even possible, but i can't see why not.

**Comment by archshift** [comment]
For sure, yes! If you have a PR that implements it, fire away.

**Comment by MathiasKoch** [comment]
Hmm. After taking a second look at this, it might not be as easy a win as initially thought.

I forgot to look at alloc/dealloc usage, and just had my eyes on Vec.

Will keep an eye on it though, in case i figure something out, though it might not be right now.

**Comment by faern** [comment]
> heapless version behind an alloc feature flag

This sounds backwards. Anything named `alloc` should use the heap, not the other way around.
