### ISSUE TITLE
Is DynStack Send + Sync?

### ISSUE THREAD

**Issue by calebmer** [archshift/dynstack#15]
`DynStack` does not auto-implement `Send` and `Sync` because it has a `*mut u8` pointer. I’m like 80% sure it is `Send` and `Sync` after quickly perusing the code and have added a wrapper in my codebase that unsafely implements `Send` and `Sync`.

Is it safe to implement `Send` and `Sync` for `DynStack`?

**Comment by calebmer** [comment]
Oh, it looks like the code in this repo is `Send`/`Sync` but the version released to Cargo is not. Could you publish a new version?

https://github.com/archshift/dynstack/blob/f4475bad4abd9ff8fdccc9d929d6f969b427dfde/src/lib.rs#L103-L104

**Comment by faern** [comment]
A lot of stuff happened in the `master` branch since the last release. It's really about time to release a new version. But let's maybe wait and see if we can get #17 merged first?

**Comment by archshift** [comment]
Published at https://crates.io/crates/dynstack/0.4.0!
