### ISSUE TITLE
Exclude huge binary files from published crate

### ISSUE THREAD

**Issue by faern** [archshift/dynstack#2]
According to crates.io this crate is 10.11 MiB large for version 0.2.0. I thought that was a bit large for what it did. So I downloaded the package directly from crates.io (with `cargo-clone`). It contains the files `vgcore.24209`, `vgcore.826`, `vgcore.894` and `vgcore.978` which are 27-31 MiB each when unpacked :sweat: Compare with version 0.1.1 which is just 5.21 kiB.

Cargo is dangerous, just includes anything you happen to have laying around in the folder when publishing. You might want to consider adding either an `exclude` field to `Cargo.toml` excluding the huge files. Or maybe an `include` field specifying exactly what you want to include instead.

**Comment by archshift** [comment]
I've fixed this with the most recent commit. Thanks for letting me know!
